BETProject/Controllers/TournamentController.cs
using BETProject.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace BETProject.Controllers
{
    [Authorize]
    public class TournamentController : Controller
    {
        readonly string baseUrl = ConfigurationManager.AppSettings["baseurl"];
        readonly string apiUrl = ConfigurationManager.AppSettings["baseurl"] + "/api/Tournaments/";

        HttpClient client;

        public TournamentController()
        {
            client = new HttpClient
            {
                BaseAddress = new Uri(apiUrl)
            };
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
        }

        public ActionResult Index(int? pageNumber)
        {   
            return View();
        }  

        [HttpPost]        
        public ActionResult Edit(TournamentViewModel tournament)
        {            
            return View(tournament);
        }
                
        public async Task<ActionResult>  Edit(int id)
        {            
            TournamentViewModel tournament = new TournamentViewModel();
            HttpResponseMessage responseMessage = await client.GetAsync(apiUrl + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                tournament = JsonConvert.DeserializeObject<TournamentViewModel>(responseData);
            }
            return View(tournament);
        }

        public async Task<ActionResult> GetTournament(int id)
        {
            TournamentViewModel tournament = new TournamentViewModel();
            HttpResponseMessage responseMessage = await client.GetAsync(apiUrl + "/" + id);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                tournament = JsonConvert.DeserializeObject<TournamentViewModel>(responseData);
            }          

            return Json(tournament, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> GetAll()
        {
            List<TournamentViewModel> tournaments = new List<TournamentViewModel>();
            HttpResponseMessage responseMessage = await client.GetAsync(apiUrl);
            if (responseMessage.IsSuccessStatusCode)
            {
                var responseData = responseMessage.Content.ReadAsStringAsync().Result;
                tournaments = JsonConvert.DeserializeObject<List<TournamentViewModel>>(responseData);
            }            
            return Json(tournaments, JsonRequestBehavior.AllowGet);            
        }

        //The Post method
        [HttpPost]
        public async Task<ActionResult> Create(TournamentViewModel tournament)
        {
            HttpResponseMessage responseMessage = await client.PostAsJsonAsync(apiUrl, tournament);
            if (responseMessage.IsSuccessStatusCode)
            {
                return Json(new { Success = true, Message = "Successfully created tournament" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, Message = "Failed creating tournament" }, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public async Task<ActionResult> Update(TournamentViewModel tournament)
        {
            HttpResponseMessage responseMessage = await client.PutAsJsonAsync(apiUrl +"/" + tournament.TournamentID, tournament);
            if (responseMessage.IsSuccessStatusCode)
            {
                return Json(new { Success = true, Message = "Successfully updated tournament" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, Message = "Failed updating tournament" }, JsonRequestBehavior.AllowGet);
        }

        //The PUT Method
        [HttpPost]
        public async Task<ActionResult> Edit(int id, TournamentViewModel tournament)
        {
            HttpResponseMessage responseMessage = await client.PutAsJsonAsync(apiUrl + "/" + id, tournament);
            if (responseMessage.IsSuccessStatusCode)
            {
                return Json(new { Success = true, Message = "Successfully updated tournament" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { Success = false, Message = "Failed updating tournament" }, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> Delete(TournamentViewModel tournament)
        {
            if (tournament.TournamentID > 0)
            {
                HttpResponseMessage responseMessage = await client.DeleteAsync(apiUrl+"/" + tournament.TournamentID);
                if (responseMessage.IsSuccessStatusCode)
                {
                    return Json(new { Success = true, Message ="Successfully deleted tournament" }, JsonRequestBehavior.AllowGet);
                }
                    
                return Json(new { Success = false, Message = "Error occured while deleting tournament" }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { Success = false, Message = "Invalid tournament object." }, JsonRequestBehavior.AllowGet);
        }

    }
}

BETProject/Views/Shared/_Layout.cshtml
@*@inject SignInManager<ApplicationUser> signInManager;*@
@using System.Security.AccessControl;

<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - B.E.T Project</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <link href="~/Content/toastr.css" rel="stylesheet" />
    <script src="~/Scripts/angular.js"></script>
    <script src="~/Scripts/angular-route.min.js"></script>
    <script src="~/Scripts/angular-route.js"></script>
    <script src="~/Scripts/app/app.js"></script>
    <script src="//angular-ui.github.io/bootstrap/ui-bootstrap-tpls-2.0.1.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("B.E.T Project", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @*@if (User.Identity.IsAuthenticated)
                    {*@
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("Role", "Index", "Role")</li>*@
                    <li>@Html.ActionLink("Tournaments", "Index", "Tournament")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @*}
                    else
                    {*@
                @Html.Partial("_LoginPartial")
                @*}*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - B.E.T Project</p>
        </footer>
    </div>

    @**@

    @RenderSection("scripts", required: false)
</body>
</html>